### ISSUE TITLE
Description element not formatted correctly for schema

### ISSUE THREAD

**Issue by jcamp** [LotarProject/dokuwiki-plugin-semantic#12]
I've looked at this and it seems to take the heading of the page and just the first 250 or 500 characters with \n (line breaks) which do not render well with Google SERP.

I suggest replacing the line breaks with Full Stops (.) and a space character. Which would make things read a lot better. Maybe single line breaks could be converted to a space as well.

Just for interest my code for that is:

```
public function getDescription() {
return (@$this->meta['description']['abstract'] ? str_replace("\n\n",". ",$this->meta['description']['abstract']): $this->getTitle());
}
```

![image](https://user-images.githubusercontent.com/148007/44351243-581c4780-a499-11e8-82ec-60164401dc6d.png)

**Comment by giterlizzi** [comment]
Hi,
Fixed with da1aaf0.

Thanks!
Joseph
