### ISSUE TITLE
multi popups in search result

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [LotarProject/dokuwiki-plugin-semantic#5]
Hi Lotar,

when you quickly hover over the search result list the popups from the semantic plugin are overlapped.
 
_Example:_
![2016-12-20 10_34_23-suche test-wiki](https://cloud.githubusercontent.com/assets/1800472/21345338/2296a714-c6a0-11e6-8cde-18cf9df641d4.png)

Best regards
Juergen

**Comment by giterlizzi** [comment]
This issue was moved to LotarProject/dokuwiki-template-bootstrap3#282
